// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package sqlitec

import (
	"database/sql"
)

type Game struct {
	ID          string
	Typ         string
	ModPassword sql.NullString
	Data        []byte
}
