#!/usr/bin/env bash

# Go to the openapi/ directory.
cd "$(dirname "${BASH_SOURCE[0]}")"

out=qg.jsonnet

main() {
	jsonnets=( $(find . -name '*.jsonnet') )
	jsonnetExpr="{}"
	for jsonnet in "${jsonnets[@]}"; do
		if [[ "$(realpath "$jsonnet")" == "$(realpath "$out")" ]]; then
			continue
		fi
		jsonnetExpr+=$'\n'"+ (import '${jsonnet}')"
	done
	echo "${jsonnetExpr}" > qg.jsonnet
}

main "$@"
