// Code generated by jtd-codegen for TypeScript v0.2.1

export type Qg = any;

export type Command =
  | CommandJeopardyPlayerIsCorrect0
  | CommandJeopardyPressButton0
  | CommandJoinGame0;

export interface CommandJeopardyPlayerIsCorrect0 {
  type: "JeopardyPlayerIsCorrect";
  data: CommandJeopardyPlayerIsCorrect;
}

export interface CommandJeopardyPressButton0 {
  type: "JeopardyPressButton";
  data: CommandJeopardyPressButton;
}

export interface CommandJoinGame0 {
  type: "JoinGame";
  data: CommandJoinGame;
}

/**
 * CommandJeopardyPlayerIsCorrect is emitted by a game moderator to indicate
 * that a player has answered a question correctly. The winning player is
 * whoever the last EventJeopardyButtonPressed event indicated. That player
 * will instantly receive the points for the question, and the game will let
 * them choose the next category and question.
 */
export type CommandJeopardyPlayerIsCorrect = any;

/**
 * CommandJeopardyPressButton is emitted when a player presses the button
 * during a question. It is only valid to emit this command when the game is
 * in the question state.
 */
export type CommandJeopardyPressButton = any;

/**
 * CommandJoinGame is sent by a client to join a game. The client (or the
 * user) supplies a game ID and a player name. The server will respond with
 * an EventJoinedGame.
 */
export interface CommandJoinGame {
  /**
   * gameID is the ID of the game to join.
   */
  gameID: string;

  /**
   * playerName is the wanted name of the user.
   */
  playerName: PlayerName;
}

/**
 * Error is returned on every API error.
 */
export interface Error {
  /**
   * Message is the error message
   */
  message: string;
}

export type Event =
  | EventGameEnded0
  | EventJeopardyBeginQuestion0
  | EventJeopardyButtonPressed0
  | EventJeopardyResumeButton0
  | EventJeopardyTurnEnded0
  | EventJoinedGame0
  | EventPlayerJoined0;

export interface EventGameEnded0 {
  type: "GameEnded";
  data: EventGameEnded;
}

export interface EventJeopardyBeginQuestion0 {
  type: "JeopardyBeginQuestion";
  data: EventJeopardyBeginQuestion;
}

export interface EventJeopardyButtonPressed0 {
  type: "JeopardyButtonPressed";
  data: EventJeopardyButtonPressed;
}

export interface EventJeopardyResumeButton0 {
  type: "JeopardyResumeButton";
  data: EventJeopardyResumeButton;
}

export interface EventJeopardyTurnEnded0 {
  type: "JeopardyTurnEnded";
  data: EventJeopardyTurnEnded;
}

export interface EventJoinedGame0 {
  type: "JoinedGame";
  data: EventJoinedGame;
}

export interface EventPlayerJoined0 {
  type: "PlayerJoined";
  data: EventPlayerJoined;
}

/**
 * EventGameEnded is emitted when the current game ends.
 */
export interface EventGameEnded {
  leaderboard: Leaderboard;
}

/**
 * EventJeopardyBeginQuestion is emitted when a question begins within this
 * Jeopardy game. It is usually emitted once the chooser player has chosen a
 * category and value.
 *
 * Each category name and question value will map to a category and question
 * within the game data. Note that a question may repeat across multiple
 * categories.
 */
export interface EventJeopardyBeginQuestion {
  category: string;
  question: string;
}

/**
 * EventJeopardyButtonPressed is emitted when any player had pressed a button
 * on their device, voiding other players' buttons. This event is only
 * emitted when the game is in the "question" state.
 */
export interface EventJeopardyButtonPressed {
  playerName: PlayerName;
}

/**
 * EventJeopardyResumeButton is emitted when the player can now continue to
 * press the button whenever they are ready to answer the question. This
 * could happen if the other player who pressed the button first got the
 * question wrong.
 *
 * Note that if alreadyPressed is true, then the player has already pressed
 * the button, so they cannot press it again.
 */
export interface EventJeopardyResumeButton {
  alreadyPressed: boolean;
}

/**
 * EventJeopardyTurnEnded is emitted when a turn ends or when the game first
 * starts.
 */
export interface EventJeopardyTurnEnded {
  currentScore: number;
  isChooser: boolean;
  leaderboard: Leaderboard;
}

/**
 * EventJoinedGame is emitted when the current player joins a game. It is a
 * reply to CommandJoinGame and is only for the current player. Not to be
 * confused with EventPlayerJoinedGame, which is emitted when any player
 * joins the current game.
 */
export type EventJoinedGame = Game;

/**
 * EventPlayerJoined is emitted when a player joins the current game.
 */
export interface EventPlayerJoined {
  playerName: PlayerName;
}

/**
 * Game is the main game object. It contains all the information about the
 * game.
 */
export type Game = GameJeopardy | GameKahoot;

export interface GameJeopardy {
  game: "jeopardy";
  data: Jeopardy;
}

export interface GameKahoot {
  game: "kahoot";
  data: Kahoot;
}

/**
 * JeopardyGame is the game data for a Jeopardy game.
 */
export interface Jeopardy {
  categories: JeopardyCategory[];

  /**
   * moderators enables moderators being able to join.
   */
  moderators?: boolean;

  /**
   * require_name, if true, will require members to input a name before
   * we can participate.
   */
  require_name?: boolean;

  /**
   * score_multiplier is the score multiplier for each question. The
   * default is 100.
   */
  score_multiplier?: number;
}

/**
 * JeopardyCategory is a category in a Jeopardy game.
 */
export interface JeopardyCategory {
  /**
   * name is the name of the category.
   */
  name: string;

  /**
   * questions are the questions in the category.
   */
  questions: JeopardyQuestion[];
}

/**
 * JeopardyQuestion is a question in a Jeopardy game.
 */
export interface JeopardyQuestion {
  /**
   * answers are the possible answers.
   */
  answers: string[];

  /**
   * correct_answer is the correct answer within the list of answers
   * above. The index starts at 1.
   */
  correct_answer: number;

  /**
   * question is the question.
   */
  question: string;
}

/**
 * KahootGame is the game data for a Kahoot game.
 */
export interface Kahoot {
  /**
   * questions are the questions in the game.
   */
  questions: KahootQuestion[];

  /**
   * time_limit is the time limit for each question. The format is in
   * Go's time.Duration, e.g. 10s for 10 seconds.
   */
  time_limit: string;
}

/**
 * KahootQuestion is a question in a Kahoot game.
 */
export interface KahootQuestion {
  /**
   * answers are the possible answers.
   */
  answers: string[];

  /**
   * question is the question.
   */
  question: string;
}

/**
 * Leaderboard is a list of players and their scores.
 */
export type Leaderboard = LeaderboardEntry[];

export interface LeaderboardEntry {
  playerName: string;
  score: number;
}

/**
 * PlayerName is the name of a player.
 */
export type PlayerName = string;
