#!/usr/bin/env bash
set -euo pipefail

srcdir=$(realpath "$(dirname "$0")/..")
cd "$srcdir"

pids=()

(caddy run --watch --config ./scripts/Caddyfile) &
pids+=($!)

(go run ./backend --addr localhost:8081) &
pids+=($!)

(vite dev --port 8082 | cat) &
pids+=($!)

sleep 1
xdg-open http://localhost:8080

trap 'kill -INT ${pids[*]}' EXIT
wait ${pids[*]}
