// Code generated by jtd-go-validators. DO NOT EDIT.

package qg

// Validate validates the Command object. It implements the
// Validator interface.
func (v *Command) Validate() error {
	return Validate("Command", v)
}

// Validate validates the Error object. It implements the
// Validator interface.
func (v *Error) Validate() error {
	return Validate("Error", v)
}

// Validate validates the Event object. It implements the
// Validator interface.
func (v *Event) Validate() error {
	return Validate("Event", v)
}

// Validate validates the GameData object. It implements the
// Validator interface.
func (v *GameData) Validate() error {
	return Validate("GameData", v)
}

// Validate validates the JeopardyCategory object. It implements the
// Validator interface.
func (v *JeopardyCategory) Validate() error {
	return Validate("JeopardyCategory", v)
}

// Validate validates the JeopardyGameInfo object. It implements the
// Validator interface.
func (v *JeopardyGameInfo) Validate() error {
	return Validate("JeopardyGameInfo", v)
}

// Validate validates the JeopardyQuestion object. It implements the
// Validator interface.
func (v *JeopardyQuestion) Validate() error {
	return Validate("JeopardyQuestion", v)
}

// Validate validates the KahootGameData object. It implements the
// Validator interface.
func (v *KahootGameData) Validate() error {
	return Validate("KahootGameData", v)
}

// Validate validates the KahootQuestion object. It implements the
// Validator interface.
func (v *KahootQuestion) Validate() error {
	return Validate("KahootQuestion", v)
}

// Validate validates the LeaderboardEntry object. It implements the
// Validator interface.
func (v *LeaderboardEntry) Validate() error {
	return Validate("LeaderboardEntry", v)
}

// Validate validates the RequestGetGame object. It implements the
// Validator interface.
func (v *RequestGetGame) Validate() error {
	return Validate("RequestGetGame", v)
}

// Validate validates the RequestGetJeopardyGame object. It implements the
// Validator interface.
func (v *RequestGetJeopardyGame) Validate() error {
	return Validate("RequestGetJeopardyGame", v)
}

// Validate validates the RequestNewGame object. It implements the
// Validator interface.
func (v *RequestNewGame) Validate() error {
	return Validate("RequestNewGame", v)
}

// Validate validates the ResponseGetGame object. It implements the
// Validator interface.
func (v *ResponseGetGame) Validate() error {
	return Validate("ResponseGetGame", v)
}

// Validate validates the ResponseGetJeopardyGame object. It implements the
// Validator interface.
func (v *ResponseGetJeopardyGame) Validate() error {
	return Validate("ResponseGetJeopardyGame", v)
}

// Validate validates the ResponseNewGame object. It implements the
// Validator interface.
func (v *ResponseNewGame) Validate() error {
	return Validate("ResponseNewGame", v)
}
